# Generated by Django 3.1.5 on 2021-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autocategory',
            options={'verbose_name': 'Категория в автопарке', 'verbose_name_plural': 'Категории в автопарке'},
        ),
        migrations.AlterModelOptions(
            name='autosubcategory',
            options={'verbose_name': 'Подкатегория в автопарке', 'verbose_name_plural': 'Подкатегория в автопарке'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AlterModelOptions(
            name='caroptions',
            options={'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Отображать?'),
        ),
        migrations.AddField(
            model_name='car',
            name='show_at_index',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной?'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_at_index',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной?'),
        ),
        migrations.AlterField(
            model_name='car',
            name='option',
            field=models.ManyToManyField(blank=True, related_name='options', to='api.CarOptions', verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='car',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='services', to='api.Service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='caroptions',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Опция'),
        ),
    ]
